spring:
  application:
    name: admin-server
    # 数据库访问配置,主数据源，默认的
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.52.79.108:3306/auth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    # 初始化大小，最小，最大
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
#mybatis-plus
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/mistra/axela/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lyj.admin.domain
  configuration:
    #打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
oauth2:
  ignorePatterns:
    - /actuator/**
    - /webjars/**
    - /resources/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /v2/api-docs
swagger2:
  basePackage: com.lyj.admin
  title: '后台管理系统API文档'
  version: '0.7'
  description: '无'
  contact-name: '刘云杰'
  contact-url: 'http://132.232.17.78'
  contact-email: '1264415695@qq.com'
security:
  oauth2:
    client:
      client-id: admin
      client-secret: 123456
      access-token-uri: http://${AUTH-HOST:localhost}:8040/oauth/token
      user-authorization-uri: http://${AUTH-HOST:localhost}:8040/oauth/authorize
      grant-type: password
      scope: read
    resource:
      user-info-uri: http://${AUTH-HOST:localhost}:8040/user/info
      token-info-uri: http://${AUTH-HOST:localhost}:8040/oauth/check_token
      prefer-token-info: false