spring:
  application:
    name: auth-server
  jpa:
    show-sql: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.52.79.108:3306/auth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    host: 47.52.79.108
    port: 6379
    password: 123456
    timeout: 30000
oauth2:
  ignore:
    patterns: /oauth/**,/user,/actuator/**,/webjars/**,/resources/**,/swagger-ui.html,/swagger-resources/**,/v2/api-docs
swagger2:
  basePackage: com.lyj.auth
  title: '权限服务API文档'
  version: '0.7'
  description: '无'
  contact-name: '刘云杰'
  contact-url: 'http://132.232.17.78'
  contact-email: '1264415695@qq.com'