spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters: SwaggerHeaderFilter

logging:
  level:
    org.springframework.cloud.gateway: debug